version: '3.3'
services:
  db:
    image: postgres
    restart: always
    container_name: postgreSQL-Database
    environment:
      POSTGRES_DB: drawing
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: camp@stcon.org
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "9101:80"
    links:
      - "db:pgsql-server"